name: dispatch build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
      release:
        required: true
        default: false
        type: boolean
      prev-version:
        required: false

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64", "arm64"]
        os: ["linux"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.24.0'
      - id: build
        run: make binaries
        env:
          ARCH: ${{ matrix.arch }}
          OS: ${{ matrix.os }}
          VERSION: ${{ inputs.version }}
      - id: upload-zip-binaries
        uses: actions/upload-artifact@v6
        with:
          name: wg-exchange-${{ matrix.os }}-${{ matrix.arch }}
          path: wg-exchange-${{ matrix.os }}-${{ matrix.arch }}.tar.zst
          compression-level: 0
          overwrite: true
  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.release }}
    steps:
      - uses: actions/checkout@v6
      - id: download-artifacts
        uses: actions/download-artifact@v7
      - id: release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: "${{ steps.download-artifacts.outputs.download-path }}/**/*.tar.zst"
          artifactErrorsFailBuild: true
          tag: v${{ inputs.version }}
          commit: master
          immutableCreate: true
          generateReleaseNotes: true
          generateReleaseNotesPreviousTag: ${{ inputs.prev-version != '' && format('v{0}', inputs.prev-version) || '' }}
